const { executeQuery } = require('../queries/neo4j_client');

/**
 * Service to analyze relationships and criminal networks in the Knowledge Graph.
 * Addresses Requirements #2 (Relationship Intelligence) and #4 (Criminal Network).
 */
class NetworkAnalysisService {
    
    /**
     * Finds relationships between two entities up to a given depth.
     * @param {string} entity1Name 
     * @param {string} entity2Name 
     * @param {number} maxDepth 
     */
    async findConnectionPath(entity1Name, entity2Name, maxDepth = 4) {
        const query = `
            MATCH p = shortestPath((a:Person {name: $entity1Name})-[:KNOWS|INVOLVED_IN|OWNS|CALLED*1..${maxDepth}]-(b:Person {name: $entity2Name}))
            RETURN p
        `;
        
        try {
            const results = await executeQuery(query, { entity1Name, entity2Name });
            return results;
        } catch (error) {
            console.error("Error finding connection path", error);
            throw error;
        }
    }

    /**
     * Detects potential gangs by finding heavily connected clusters of persons.
     */
    async detectGangs() {
        // Community detection using simple graph traversal or Graph Data Science (GDS) library if installed.
        // For standard Neo4j without GDS, we can find triangles or highly connected nodes.
        const query = `
            MATCH (p1:Person)-[:KNOWS]-(p2:Person)-[:KNOWS]-(p3:Person)-[:KNOWS]-(p1)
            RETURN p1.name AS Member1, p2.name AS Member2, p3.name AS Member3
            LIMIT 50
        `;
        
        try {
            const results = await executeQuery(query);
            return results;
        } catch (error) {
            console.error("Error detecting gangs", error);
            throw error;
        }
    }

    /**
     * Ingests entities generated by the EntityExtractionService into Neo4j
     * @param {Object} entities 
     * @param {string} caseId 
     */
    async ingestEntities(entities, caseId) {
        // This is a basic representation. A production system would handle MERGE efficiently.
        if (!entities) return;

        // Create Case Node
        await executeQuery(`MERGE (c:Case {id: $caseId})`, { caseId });

        if (entities.suspects) {
            for (const suspect of entities.suspects) {
                const query = `
                    MERGE (p:Person {name: $name})
                    MERGE (c:Case {id: $caseId})
                    MERGE (p)-[:SUSPECT_IN]->(c)
                `;
                await executeQuery(query, { name: suspect.name || 'Unknown', caseId });
                
                // Handle identifiers (e.g. phone numbers)
                if (suspect.identifiers && suspect.identifiers.length > 0) {
                    for (const identifier of suspect.identifiers) {
                        await executeQuery(`
                            MERGE (p:Person {name: $name})
                            MERGE (id:Identifier {value: $identifier})
                            MERGE (p)-[:HAS_IDENTIFIER]->(id)
                        `, { name: suspect.name || 'Unknown', identifier });
                    }
                }
            }
        }

        if (entities.locations) {
            for (const loc of entities.locations) {
                await executeQuery(`
                    MERGE (l:Location {name: $loc})
                    MERGE (c:Case {id: $caseId})
                    MERGE (c)-[:OCCURRED_AT]->(l)
                `, { loc, caseId });
            }
        }
        
        return true;
    }
}

module.exports = new NetworkAnalysisService();
