const LLMService = require('../services/LLMService');
const { evidenceSystemPrompt } = require('../prompts/evidencePrompt');

class EvidenceAgent {
    static async correlateEvidence(rawData) {
        const messages = [
            { role: "system", content: evidenceSystemPrompt },
            { role: "user", content: `Raw datastore results:\n${JSON.stringify(rawData)}` }
        ];

        try {
            console.log(`[EvidenceAgent] Correlating evidence via LLMService...`);
            const responseMessage = await LLMService.generate(messages, { maxTokens: 1536 });
            let content = responseMessage.content.trim();
            
            if (content.startsWith("```json")) {
                content = content.replace(/^```json\n?/, "").replace(/\n?```$/, "");
            }

            // Extract array first
            const arrayMatch = content.match(/\[[\s\S]*\]/);
            if (arrayMatch) {
                content = arrayMatch[0];
            }

            let ledger = JSON.parse(content);
            
            if (!Array.isArray(ledger)) {
                if (ledger && typeof ledger === 'object') {
                    ledger = [ledger];
                } else {
                    ledger = [];
                }
            }

            return ledger.map(item => ({
                claim: item.claim || "AI Correlation Event",
                evidence: item.evidence || JSON.stringify(item),
                sourceTable: item.sourceTable || "Unknown",
                recordId: item.recordId || "Unknown",
                confidence: typeof item.confidence === 'number' ? item.confidence : parseInt(item.confidence) || 0,
                reason: item.reason || item.reasoning || "Generated by AI",
                counterEvidence: item.counterEvidence || item.counter || "None",
                suggestedNextAction: item.suggestedNextAction || "Review manual case files"
            }));
        } catch (error) {
            console.error("[EvidenceAgent] Error correlating evidence:", error);
            
            // If LLM fails, return the raw data so the fallback synthesizer can render actual database records!
            let fallbackLedger = [];
            if (Array.isArray(rawData)) {
                fallbackLedger = rawData;
            } else if (rawData && typeof rawData === 'object') {
                // If it's a map of tool results, flatten it
                for (const key in rawData) {
                    if (Array.isArray(rawData[key])) {
                        fallbackLedger = fallbackLedger.concat(rawData[key]);
                    } else if (rawData[key]) {
                        fallbackLedger.push(rawData[key]);
                    }
                }
            }
            
            return fallbackLedger;
        }
    }
}

module.exports = EvidenceAgent;
