const LLMService = require('../services/LLMService');
const { copilotSystemPrompt } = require('../prompts/copilotPrompt');
const HallucinationGuardService = require('../services/HallucinationGuardService');

class ReportAgent {
    static generateStandardReport(ledger) {
        if (!ledger || ledger.length === 0) {
            return `# Executive Summary\n- Data unavailable. No active records found for this case context.`;
        }

        const ledgerArray = Array.isArray(ledger) ? ledger : [ledger];
        const context = ledgerArray.find(l => l._type === 'FullCaseContext') || ledgerArray[0];
        
        let report = `# OFFICIAL INVESTIGATION DOCKET & AI REPORT
Generated by VIKSHANA Intelligence System

---
## PART I: VERIFIED DATABASE FACTS
*The following information is retrieved directly from the Catalyst Datastore.*

### 1. FIR & Case Details
- **Case Number:** ${context.case?.caseNumber || 'Data unavailable'}
- **Date Registered:** ${context.case?.date ? new Date(context.case.date).toLocaleDateString() : 'Data unavailable'}
- **Primary Category:** ${context.case?.category || 'Data unavailable'}
- **Jurisdiction:** ${context.case?.jurisdiction || 'Data unavailable'}

**Brief Facts:**
${context.case?.briefFacts || 'Data unavailable.'}

### 2. Accused & Suspects
`;

        if (context.suspects && context.suspects.length > 0) {
            context.suspects.forEach(s => {
                report += `- **Name:** ${s.name || 'Unknown'} (Age: ${s.age || 'N/A'}, Gender: ${s.gender || 'N/A'})\n`;
            });
        } else {
            report += `*No accused records identified in datastore.* \n`;
        }

        report += `
### 3. Timeline of Verified Events
| Time | Event Description |
|------|-------------------|`;

        if (context.timeline && context.timeline.length > 0) {
            context.timeline.forEach(t => {
                const timeStr = t.event_time ? new Date(t.event_time).toLocaleString() : 'Unknown Time';
                report += `\n| ${timeStr} | ${t.title || 'Event'}: ${t.description || 'Details unavailable'} |`;
            });
        } else {
            report += `\n| Data unavailable | Data unavailable |`;
        }

        report += `\n\n---
## PART II: AI FINDINGS & RECOMMENDATIONS
*The following intelligence is derived deterministically from the facts above. It must be verified by an investigator.*

### 1. Investigation Gaps Identified
`;
        if (context.gaps && context.gaps.length > 0) {
            context.gaps.forEach(g => {
                report += `- **Gap:** ${g.gap || 'Unknown'} \n  *Recommendation:* ${g.recommendedAction || 'N/A'}\n`;
            });
        } else {
            report += `- No obvious investigation gaps detected based on available records.\n`;
        }

        report += `
### 2. Evidence Trail & Limitations
- **Records Evaluated:** ${context.timeline?.length || 0} timeline events, ${context.suspects?.length || 0} suspects.
- **Limitation Notice:** This report evaluates ONLY the digital records present in the Catalyst Datastore. It does not account for physical evidence not yet uploaded or witness statements pending transcription.

---
**CONFIDENTIAL // LAW ENFORCEMENT SENSITIVE**
`;

        return report.trim();
    }

    static async generateReport(ledger, history = [], res, streaming) {
        // Fallback checks for simple greetings
        const lastUserMsg = Array.isArray(history) && history.length > 0 ? [...history].reverse().find(m => m.role === 'user') : null;
        const userText = lastUserMsg ? lastUserMsg.content : '';
        const cleanText = userText ? userText.trim().toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g,"") : "";
        const greetings = ['hi', 'hello', 'hey', 'hi there', 'greetings', 'yo'];
        
        // Report generation command (fallback if user explicitly wants full report)
        if (history.length === 0 || cleanText.includes("generate report") || cleanText.includes("full report")) {
            const report = this.generateStandardReport(ledger);
            if (streaming && res && !res.writableEnded) {
                const chunks = report.split(' ');
                for (let i = 0; i < chunks.length; i += 3) {
                    if (res.writableEnded || res.destroyed) break;
                    LLMService.sendEvent(res, 'delta', { text: chunks.slice(i, i + 3).join(' ') + ' ' });
                    await new Promise(r => setTimeout(r, 18));
                }
            }
            return report;
        }

        if (greetings.includes(cleanText)) {
            const reply = "Hi, I'm Vikshana AI. What can I do for you?";
            if (streaming && res && !res.writableEnded) {
                const chunks = reply.split(' ');
                for (let i = 0; i < chunks.length; i += 3) {
                    if (res.writableEnded || res.destroyed) break;
                    LLMService.sendEvent(res, 'delta', { text: chunks.slice(i, i + 3).join(' ') + ' ' });
                    await new Promise(r => setTimeout(r, 18));
                }
            }
            return reply;
        }

        const messages = [
            { role: "system", content: copilotSystemPrompt }
        ];

        // Add history (limit to last 4 messages)
        const recentHistory = history.slice(-4);
        for (const msg of recentHistory) {
            messages.push({ role: msg.role === 'assistant' ? 'assistant' : 'user', content: msg.content });
        }

        messages.push({ 
            role: "user", 
            content: `Evidence Ledger:\n${JSON.stringify(ledger)}` 
        });

        try {
            console.log(`[ReportAgent] Generating strictly verified JSON response...`);
            
            const StructuredAIResponseParser = require('../services/StructuredAIResponseParser');
            let responseMessage = await LLMService.generate(messages, { maxTokens: 8192, temperature: 0.1 });
            let parsedResult = StructuredAIResponseParser.parse(responseMessage);

            if (parsedResult.status === 'TRUNCATED_OUTPUT' || parsedResult.status === 'MALFORMED_JSON') {
                console.warn("[ReportAgent] AI response was truncated or malformed. Retrying once...");
                messages.push({ role: 'assistant', content: parsedResult.rawContent });
                messages.push({ role: 'user', content: "Generate a concise evidence-grounded report. Do not include unnecessary prose. Return only the required structured fields. Prioritize completing the JSON structure." });
                responseMessage = await LLMService.generate(messages, { maxTokens: 8192, temperature: 0.1 });
                parsedResult = StructuredAIResponseParser.parse(responseMessage);
            }

            if (parsedResult.status !== 'VALID_JSON') {
                console.error(`[ReportAgent] Generation completely failed: ${parsedResult.status}`);
                const errorMarkdown = `> **🔴 GENERATION FAILED**\n\nThe analytical report could not be generated completely (Provider error or Token limit reached).`;
                if (streaming && res && !res.writableEnded) {
                    const chunks = errorMarkdown.split(' ');
                    for (let i = 0; i < chunks.length; i += 3) {
                        if (res.writableEnded || res.destroyed) break;
                        LLMService.sendEvent(res, 'delta', { text: chunks.slice(i, i + 3).join(' ') + ' ' });
                        await new Promise(r => setTimeout(r, 18));
                    }
                }
                return errorMarkdown;
            }

            let parsedResponse = parsedResult.data;

            // Post-Generation Deterministic Validation
            parsedResponse = HallucinationGuardService.validate(parsedResponse, ledger);

            // Compile structured schema into Markdown for the UI
            let compiledAnswer = `### Summary\n${parsedResponse.summary || 'No summary provided.'}\n\n`;
            
            if (parsedResponse.key_findings && parsedResponse.key_findings.length > 0) {
                compiledAnswer += `### Key Findings\n` + parsedResponse.key_findings.map(f => `- ${f}`).join('\n') + `\n\n`;
            }
            if (parsedResponse.timeline && parsedResponse.timeline.length > 0) {
                compiledAnswer += `### Timeline\n` + parsedResponse.timeline.map(t => `- ${t}`).join('\n') + `\n\n`;
            }
            if (parsedResponse.evidence_analysis && parsedResponse.evidence_analysis.length > 0) {
                compiledAnswer += `### Evidence Analysis\n` + parsedResponse.evidence_analysis.map(e => `- ${e}`).join('\n') + `\n\n`;
            }
            if (parsedResponse.investigation_gaps && parsedResponse.investigation_gaps.length > 0) {
                compiledAnswer += `### Investigation Gaps\n` + parsedResponse.investigation_gaps.map(g => `- ${g}`).join('\n') + `\n\n`;
            }
            if (parsedResponse.limitation) {
                compiledAnswer += `### Limitations\n> ${parsedResponse.limitation}\n\n`;
            }

            // Format for the UI using native Markdown
            let badgeIcon = "⚪";
            if (parsedResponse.evidenceStatus === "CONFIRMED") badgeIcon = "🟢";
            if (parsedResponse.evidenceStatus === "EVIDENCE_BACKED") badgeIcon = "🔵";
            if (parsedResponse.evidenceStatus === "AI_INFERRED") badgeIcon = "🟠";
            if (parsedResponse.evidenceStatus === "UNAVAILABLE") badgeIcon = "🔴";

            let finalMarkdown = `> **${badgeIcon} EVIDENCE STATUS: ${parsedResponse.evidenceStatus || 'UNAVAILABLE'}**\n\n${compiledAnswer.trim()}`;
            
            if (parsedResponse.sources && parsedResponse.sources.length > 0) {
                finalMarkdown += `\n\n*Sources: ${parsedResponse.sources.join(', ')}*`;
            }

            // Fake stream it to the client to maintain UX
            if (streaming && res && !res.writableEnded) {
                const chunks = finalMarkdown.split(' ');
                for (let i = 0; i < chunks.length; i += 3) {
                    if (res.writableEnded || res.destroyed) break;
                    LLMService.sendEvent(res, 'delta', { text: chunks.slice(i, i + 3).join(' ') + ' ' });
                    await new Promise(r => setTimeout(r, 18));
                }
            }
            
            return finalMarkdown;
        } catch (error) {
            console.error("[ReportAgent] Error generating response, using fallback:", error.message);
            const fallbackMsg = `> **🔴 GENERATION FAILED**\n\nAn unexpected error occurred during generation: ${error.message}`;
            if (streaming && res && !res.writableEnded) {
                const chunks = fallbackMsg.split(' ');
                for (let i=0; i<chunks.length; i+=3) {
                    if (res.writableEnded || res.destroyed) break;
                    LLMService.sendEvent(res, 'delta', { text: chunks.slice(i, i+3).join(' ') + ' ' });
                    await new Promise(r => setTimeout(r, 18));
                }
            }
            return fallbackMsg;
        }
    }
}

module.exports = ReportAgent;
